global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
  static_layer:
    plugin: "nav2_costmap_2d::StaticLayer"
  obstacle_layer:
    plugin: "nav2_costmap_2d::ObstacleLayer"
  inflation_layer:
    plugin: "nav2_costmap_2d::InflationLayer"
