explore:
  ros__parameters:
    ### Core Configuration ###
    robot_base_frame: "base_link"
    costmap_topic: "/global_costmap/costmap"
    costmap_updates_topic: "/global_costmap/costmap_updates"
    odom_topic: "/odometry/filtered"  # Ensure this matches your EKF output
    scan_topic: "/scan"               # Verify your LIDAR topic
    
    ### Exploration Behavior ###
    explore_frequency: 1.0            # Hz (lower for large maps)
    planner_frequency: 0.5            # Hz (should be ≤ explore_frequency)
    min_frontier_size: 0.5            # meters (smaller = more frontiers)
    potential_scale: 1.0              # Weight for frontier potential
    gain_scale: 1.0                   # Weight for frontier gain
    progress_timeout: 30.0            # Seconds before giving up
    
    ### Safety Parameters ###
    transform_tolerance: 0.5          # TF tolerance (seconds)
    min_exploration_time: 10.0        # Minimum exploration duration
    
    ### Visualization ###
    visualize: true                   # RViz markers
    frontier_travel_point: "closest"  # ["closest", "middle", "centroid"]
    
    ### Advanced ###
    potential_cutoff: 10.0            # Max frontier attraction
    orientation_scale: 0.0            # Weight for orientation adjustment
    max_exploration_time: 3600.0      # Timeout (1 hour)
    replanning_enabled: true